id: DB0C4C70C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:37:58+00:00'
last_modified: '2022-05-26T11:49:04.879999+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    54a2:
      image_group_id: I1PD95873
      title: དཀྱིལ་འཁོར་གྱི་ཐིག་གི་ཆོ་ག།
      total_pages: 1445
      order: 28
      base_file: 54a2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
